{% set name = "JayDeBeApi" %}
{% set version = "1.2.2" %}
{% set sha256 = "e9847e437ad293ee3cc47767b74c387068cd21607842de8470d5d3f13d613083" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - jpype1

test:
  imports:
    - jaydebeapi

about:
  home: https://github.com/baztian/jaydebeapi
  license: LGPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: A Python DB-APIv2.0 compliant library for JDBC Drivers

  description: |
    The JayDeBeApi module allows you to connect from Python code to
    databases using Java JDBC. It provides a Python DB-API v2.0 to that
    database.

    It works on ordinary Python (cPython) using the JPype Java
    integration or on Jython to make use of the Java JDBC driver.

    In contrast to zxJDBC from the Jython project JayDeBeApi let's you
    access a database with Jython AND Python with only minor code
    modifications. JayDeBeApi's future goal is to provide a unique and
    fast interface to different types of JDBC-Drivers through a flexible
    plug-in mechanism.
  dev_url: https://github.com/baztian/jaydebeapi

extra:
  recipe-maintainers:
    - sodre
